apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: prod-eks-private
  region: us-east-1

vpc:
  cidr: "10.0.0.0/16"
  nat:
    gateway: Single

nodeGroups:
  - name: private-ng
    instanceType: t3.medium
    desiredCapacity: 2
    privateNetworking: true
