apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: prod-eks-private
  region: us-east-1
  version: "1.29"

vpc:
  clusterEndpoints:
    privateAccess: true
    publicAccess: false

iam:
  withOIDC: true
