apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: multi-tenant-eks
  region: us-east-1
  version: "1.29"

vpc:
  nat:
    gateway: Single
  clusterEndpoints:
    privateAccess: true
    publicAccess: true

managedNodeGroups:
  - name: private-ng
    instanceType: t3.medium
    desiredCapacity: 3
    privateNetworking: true
